server:
  port: 8080
spring:
  application:
    name: e-toll-zuul-gateway
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: admin
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
security:
  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:9000/uaa/user
      preferTokenInfo: false
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG