spring:
  application:
    name: e-toll-usage-service
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: admin
server:
  port: 8002
security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user